"""create tables

Revision ID: 582986bdf07b
Revises: 9b38f5eea7c4
Create Date: 2023-10-23 23:27:24.784733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582986bdf07b'
down_revision: Union[str, None] = '9b38f5eea7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'medical_records', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_column('medical_records', 'doctor_id')
    # ### end Alembic commands ###
